// Code generated by qtc from "card.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/partial/card.qtpl:1
package partial

//line view/partial/card.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/partial/card.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/partial/card.qtpl:1
func StreamCard(qw422016 *qt422016.Writer, body string) {
//line view/partial/card.qtpl:1
	qw422016.N().S(`
  <div class="card">
    <div class="card-content">
      `)
//line view/partial/card.qtpl:4
	qw422016.N().S(body)
//line view/partial/card.qtpl:4
	qw422016.N().S(`
    </div>
  </div>
`)
//line view/partial/card.qtpl:7
}

//line view/partial/card.qtpl:7
func WriteCard(qq422016 qtio422016.Writer, body string) {
//line view/partial/card.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/partial/card.qtpl:7
	StreamCard(qw422016, body)
//line view/partial/card.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line view/partial/card.qtpl:7
}

//line view/partial/card.qtpl:7
func Card(body string) string {
//line view/partial/card.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line view/partial/card.qtpl:7
	WriteCard(qb422016, body)
//line view/partial/card.qtpl:7
	qs422016 := string(qb422016.B)
//line view/partial/card.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line view/partial/card.qtpl:7
	return qs422016
//line view/partial/card.qtpl:7
}
